### ISSUE TITLE
Background patch, Firefox and i3 issue

### ISSUE THREAD

**Issue by TomaszGasior** [lah7/gtk3-classic#11]
Issue from AUR comment: https://aur.archlinux.org/packages/gtk3-mushrooms/

@streetwalrus
> The new window background patch somewhat breaks Firefox (nightly), at least on i3. The main window shows up on all workspaces, above everything else, and will sometimes have glitched contents.

**Comment by TomaszGasior** [comment]
— Problem exists only with Nightly? It's possible to replicate it on standard Fx release?
— Only i3 window manager is affected?
— What about other GTK3 apps?

**Comment by TomaszGasior** [comment]
I am not able to reproduce this problem. I tested i3 with default config and Firefox Nigthly downloaded from Mozilla website.

Comparing 3.22.30-1 and 3.22.30-2 releases of `gtk3-mushrooms` on i3, I see only one difference. With 3.22.30-2 there is ugly black "flash" effect when window is shown. This effect is not visible with 3.22.30-1.

In GTK2 windows were initially filled by theme background color. The same in earlier GTK3 versions. In current GTK3 — windows are initially transparent but because of buggy default GDK behavior, sometimes windows are filled by solid black color. In next GTK3 release, GDK will not be filling initially windows with black color, instead windows will be always initially transparent.
There was a patch (from gnome's bugzilla) in `gtk3-mushrooms` 3.22.30-1 which was setting proper theme background color for newly created windows. So with `gtk3-mushrooms` 3.22.30-1  all windows were initially filled by theme background color. I removed this patch and in `gtk3-mushrooms` 3.22.30-2 there is a another patch, which will be part of next GTK3 release, which enforces transparency of newly created windows.

It seems to me, i3 is not able to properly behave in this context and draws black color on newly created windows. With current `gtk3-mushrooms`, in xfwm4 (XFCE4 wm) and marco (MATE wm) I have not black "flash" effect, even when compositor is off.

**Comment by 9ary** [comment]
I've only tried firefox-nightly from Heftig's repo on i3-git. Other GTK3 apps such as pavucontrol seem to behave properly. I'll do more testing tomorrow.
I'm 100% sure it's related to this patch, as removing it from the PKGBUILD fixes the issue.

**Comment by 9ary** [comment]
I've just done more testing, it turns out the problem is triggered by i3's layout restore feature and affects all GTK3 applications. Here's how to reproduce:
- Create a `layout.json` with the following contents:
```json
{
    "nodes": [
        {
            "swallows": [
               {
                  "class": "^Pavucontrol$"
               }
            ]
        }
    ]
}
```
- Run `i3-msg append_layout layout.json` (may require an absolute path)
- Run pavucontrol
- Observe the effects

I was able to reproduce this on the "stable" version of i3 in [community] as well.

**Comment by TomaszGasior** [comment]
I will try to this today in the evening. Thanks for info! Propabbly i will restore removed patch but only for disabled composition. (i3 doesn't use composition, right?)

**Comment by 9ary** [comment]
i3 itself isn't a compositing WM, but you can run a standalone compositor alongside (I've tried both with and without compton).

**Comment by 9ary** [comment]
I can also reproduce this with the unmodified upstream gtk-3-24 branch, maybe I should take this issue there or to i3?

**Comment by TomaszGasior** [comment]
Thanks for detailed information. Now I am able to reproduce this problem. It seems to me this is a bug in i3 wm, not in gtk3 but I am not GTK expert. ;)

Yes, if you can, take this issue to i3wm authors. Please, mention about this commit on GTK's repository:
https://github.com/GNOME/gtk/commit/2ce63a86ba689aa41eb47409c889c469497478b0

There is a bug in GTK3 or i3wm, not in gtk3-mushrooms, so now I am closing this issue. Thanks for info!

**Comment by TomaszGasior** [comment]
@Streetwalrus I restored old window background patch without removing new. Old patch is activated only when compositor is off. So as temporary solution (until i3 author does not fix it) please disable composition and try to the newest gtk3-mushrooms — it should be fine.

**Comment by 9ary** [comment]
I don't think doing this is going to help if you're keeping the new patch anyway. Considering it's going to be included in future GTK releases, it really ought to be fixed properly. I've reported the problem to i3 developers [here](https://github.com/i3/i3/issues/3297), and I'll try to help with it whenever I have the time for it.

Edit: spoke too soon, having both patches actually help as long as both codepaths are taken.

**Comment by TomaszGasior** [comment]
I restored old patch only for users without composition. It's needed in also in other cases, for example when you are moving one window under other window (instead black color, theme color is shown in rendered parts of window)

**Comment by 9ary** [comment]
Yeah I know that. Upstream doesn't want this because they don't really support using GTK without a compositor (understandably so). I'm currently not running one because compton is awful on amdgpu these days but I'm working on a solution for that.
