### ISSUE TITLE
Patch paths

### ISSUE THREAD

**Issue by Meriipu** [lah7/gtk3-classic#14]
I had to replace ./org/gtk/ with ./gtk/ and ./mod/gtk/ with ./gtk/ to get the patch to apply (gtk+-3.22.30). Is there any reason for this I am missing or is it perhaps just packaging differences?

**Comment by TomaszGasior** [comment]
How did you try to apply patch files? Did you use PKGBUILD or did you try to apply them manually? Which commands did you use?

**Comment by Meriipu** [comment]
I added one of the patches to /etc/portage/patches and just let portage attempt to apply them when building gtk+:3 
To deal with some conflict between this and a separate external patch I later cloned gtk+:3 and checkout out some version (3.22.30, I believe) and applied one of these patches with git apply and as far as I remember I had to use the changed path when applying here too.

**Comment by TomaszGasior** [comment]
Okay, thanks for the detailed information. First, "portage" name smells like Gentoo it seems to me. I am supporting Arch Linux only — there is no problem to use patches on OSes other than Arch, just **I am not** using OSes other than Arch. ;-) 

I am creating my patches by using a simple bash script. It's here: https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/create-patch.sh
It assumes that there are two subdirs in CWD: "org" with original GTK source code and "mod" witch code modified by me. Then it compares "gtk" subdir of these subdirectories and prints out a difference. 
In `PKGBUILD` (script used by Arch Linux to build custom packages) I am applying patches by patch command with additional `-p` switch — thanks to it patch command ignores some part of file paths in *.patch files. See here: https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/PKGBUILD#L124

Maybe  in the future, I will change the way of building patch files to make using it outside Arch Linux easier but currently, you have to:
* apply patches manually witch patch command and `-p` switch,
* or modify patch file as you did before.

Sorry for inconveniences.

**Comment by Meriipu** [comment]
I see. Thanks.
