### ISSUE TITLE
LXQt Support

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [lah7/gtk3-classic#15]
I understand your gtk3 project doesn't claim to support LXQt, but I have the patience to find a way to make this patch set work. I'm willing to test changes and document my findings as meticulously as possible.

In LXQt-git on Manjaro-unstable, window manager decorations are ignored for gtk3 programs. I am using xfwm, and I'm wondering if certain environment variables are to blame for this. If you know of a few environment variables I could try quickly, I'd be willing to test them.

Otherwise, I'm back to hunting the web, slogging through the millionth duplicate whining about the negatives of gtk3 CSDs. This has flooded the internet; making useful, pertinent information less accessible.

I heartily thank you for your continued work on patching gtk3's many faults!

**Comment by TomaszGasior** [comment]
Hi.

My patches should work exactly the same regardless of used desktop. I am using XFCE so I am testing gtk3-mushrooms with XFCE, sometimes with MATE or Cinnamon too. But my patches are not related to any desktop environment so I am not **supporting** any of them.

Now I will download Manjaro lxqt edition and do some tests. Stay tuned. ;)

**Comment by TomaszGasior** [comment]
I installed Manjaro LXQT edition and I found source of problem. Please read *carefully* README file of gtk3-mushrooms and its section about CSDs and environment variables: https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/README.md#client-side-decorations-only-on-xorg

To solve problem you have to `unset GTK_CSD`. Please reopen if the problem is different.

**Comment by Myrddin-Wyllt** [comment]
Deleting GTK_CSD and GTK_OVERLAY_SCROLLING in LXQt session settings isn't enough to rid me of this issue. Though per-user settings for LXQt is supposed to override system-wide configurations, the opposite seems to be happening. 

Instead of overriding the default session settings in /usr/share/lxqt/session.conf with my user settings located in ~/.config/lxqt/session.conf, the environment variables are always being set by the system-wide settings. This seems to be a bug affecting LXQt and per-user overrides. Commenting out the environment variables in /usr/share/lxqt/session.conf solved the issue.

Considering this is more an issue with LXQt, I won't reopen the issue; but I will say a mention in the README is worth adding so that others won't wonder why gtk3-mushrooms isn't working in LXQt.

The exact steps to solve:
Open LXQt Session Settings
Click the Environment (Advanced) section
Delete GTK environment variables
Find system-wide LXQt session.conf (/usr/share/lxqt/session.conf on Arch distributions)
Comment out OR Delete the two GTK environment variables
Restart session
