### ISSUE TITLE
Please add license(s).

### ISSUE THREAD

**Issue by ghost** [lah7/gtk3-classic#16]
Hello, Could I request a license(s) to your patch set?

**Comment by TomaszGasior** [comment]
Package's `PKGBUILD` file defines license as LGPL. https://github.com/TomaszGasior/gtk3-mushrooms/blob/c5f1b69b1d37a2723b043727965e65a1e7e42d01/PKGBUILD#L16 
gtk3-mushrooms is licensed the same way as GTK itself.

**Comment by ghost** [comment]
Thank you. Didn't think to check the PKGBUILD. Shame on me.
