### ISSUE TITLE
Any idea how to package/compile this on Ubuntu?

### ISSUE THREAD

**Issue by ripefig** [lah7/gtk3-classic#18]

**Comment by TomaszGasior** [comment]
You need to get to know how to apply *.patch files to Debian packages.  Google it please. Example article: https://unix.stackexchange.com/questions/324680/how-to-apply-a-patch-in-a-debian-package

Keep in mind that patches are created for the newest gtk3 version. Ubuntu often ships old gtk3 version which can be incompatible with my patches.

**Comment by lah7** [comment]
I was doing some experimenting myself and was able to compile `gtk3-mushrooms` under Ubuntu MATE 19.10 which uses GTK 3.24.8. I left an **experimental** script here:

https://gist.github.com/lah7/a4dec89e61ee2875406731b3cd0ae90d

I'm not too sure all the patches were working - which is probably just how it was compiled/linked, so please take with a pinch of salt.
