### ISSUE TITLE
PKGBUILD missing dependency gobject-introspection

### ISSUE THREAD

**Issue by krumelmonster** [lah7/gtk3-classic#19]
makepkg might fail reporting

    Package gobject-introspection-1.0 was not found in the pkg-config search path.

`gobject-introspection` is missing in makedepends.

I'd like to become maintainer of the project and AUR package, I've been using gtk3-mushrooms for quite a while, know some C and I'm confident I can contribute patches.

Anyways, please make sure to leave any suggestions for future development for us to read, maybe here in the issues. Thank you so much for the work you put into this.

**Comment by TomaszGasior** [comment]
It's great news! :) I want to transfer also GitHub copy of repository. There you can find some ideas for future development.

**Comment by TomaszGasior** [comment]
Please give me your name on aur.archilinux.org and, eventually,  your GitHub account, if you prefer to use different that this: https://github.com/krumelmonster

**Comment by TomaszGasior** [comment]
Some ideas I had before I changed my desktop to GNOME:

- make compatibility with GNOME better to allow GNOME users use some patches non-related to CSD (basically don't disable CSD on GNOME, don't change PDF reader etc.);
- don't disable CSD on Firefox even when disabled for all other windows: https://github.com/TomaszGasior/gtk3-mushrooms/issues/10
- maybe go backwards and remove/change this patch: https://github.com/TomaszGasior/gtk3-mushrooms/issues/8
- make this patch working again: "Menu bars are not covered by too high popup menus"
- https://github.com/TomaszGasior/gtk3-mushrooms/issues/7
- I had also idea to create packages for other distros like Ubuntu or Fedora by dividing current "master" branch to two separate folder and creating new for each distro package.

**Comment by TomaszGasior** [comment]
> gobject-introspection is missing in makedepends.

;)
https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/PKGBUILD#L23

**Comment by TomaszGasior** [comment]
Next ideas which I had:

- update screenshots in wiki, especially Adwaita and printing dialog,
- create new page in wiki and describe how create themes to make them compatible with gtk3-mushrooms (I don't want to say that gtk3-mushrooms requires extra work from theme author but theme needs to be created properly for gtk3 to work good with gtk3-mushrooms). You can look here for details description: https://forum.manjaro.org/t/gtk3-classic-gtk3-mushrooms-gtk3-with-my-own-patches/30230/140?u=tomaszgasior

**Comment by krumelmonster** [comment]
I'd use both this `krumelmonster` github account and the aur [`krumelmonster`](https://aur.archlinux.org/account/krumelmonster/) account. You said you'd look for a new maintainer starting Jun 1st so no hurry, maybe someone more familiar with gtk(3) shows up before then – I have fiddled around with gtk3 code when I had issues years ago and that's pretty much it by now.
I hadn't noticed there where relevant open issues, thanks for summing it up. I have packaged for Ubuntu and Fedora before so that's definitely an option although Arch users are probably pretty much the target audience; Taking i3 as a reference for people who almost definitely won't like Vanilla gtk3, Popularity contests for these Distributions say

- Debian 2.13%
- Ubuntu 0.10%
- Arch 11%

(Numbers from diferent methods)

**Comment by TomaszGasior** [comment]
Ok, so let's wait to 1 June and then I will transfer gtk3-mushrooms to you if your decision won't change.

**Comment by TomaszGasior** [comment]
@krumelmonster Are u still interested in taking ownership of gtk3-mushrooms project? If yes, can we do it today?

**Comment by TomaszGasior** [comment]
@krumelmonster  I made you as co-maintainer of `gtk3-mushrooms` package on AUR. Can I get confirmation from you whether are you still interested in that package?

**Comment by krumelmonster** [comment]
yes, you can transfer it and I'll maintain from now on

**Comment by krumelmonster** [comment]
Sorry, I don't have much internet access for a few days now which is why the transfer expired. Can you try transferring again?

**Comment by TomaszGasior** [comment]
@krumelmonster done
