### ISSUE TITLE
Update PKGBUILD maintainer information

### ISSUE THREAD

**Issue by TomaszGasior** [lah7/gtk3-classic#21]
Currently PKGBUILD refers to me as maintainer. Please update

- `Maintainer` comment on the top of file,
- `$url` field.
- Also, pinned comment on AUR page.

**Comment by oberon-manjaro** [comment]
Sorry, I'm afraid I don't understand to what you would like PKGBUILDs to be edited. Currently your own PKGBUILD here in the repo has your name under Maintainer.
What should it read instead?

**Comment by TomaszGasior** [comment]
@oberon-manjaro Since June 2019 I am not maintainer of gtk3-mushrooms. @krumelmonster is new maintainer. My suggestion is to update URLs in PKGBUILD and pinned comment on AUR website  to avoid confusion. :)

**Comment by oberon-manjaro** [comment]
I still don't understand. The AUR package is outdated since June. You are listed there as a maintainer still and the pinned comment for the AUR points here to your github repo.
Which url would you like to have specified in the package?

**Comment by TomaszGasior** [comment]
Please look at the current URL of the page. :) Current maintainer of gtk3-mushrooms is @krumelmonster, not me.

**Comment by TomaszGasior** [comment]
Both package ownership and gh repo ownership is moved from me to @krumelmonster. My suggestion is to just update URLs. I am still shown as "collaborator" by github because technically I am member of this repository. Also, PKGBUILD and AUR comments points to my name in URL because they are outdated.

**Comment by oberon-manjaro** [comment]
I see. Maybe the [PKGBUILD](https://github.com/krumelmonster/gtk3-mushrooms/blob/master/PKGBUILD) in this repo here should then be updated?
Also, the fact that the AUR package hasn't been updated since 2019-05-14 seems a little concerning, tbh...

**Comment by TomaszGasior** [comment]
Yes because it's exactly the same repo. :) Just https://github.com/TomaszGasior/gtk3-mushrooms redirects to https://github.com/krumelmonster/gtk3-mushrooms Updating PKGBUILD is main concern of this issue.

For some reason @krumelmonster  is not active now. Unfortunately, I don't know exactly why.

**Comment by oberon-manjaro** [comment]
Hm. Now I understand.

**Comment by krumelmonster** [comment]
I will take care of this tomorrow

**Comment by TomaszGasior** [comment]
Thx, @krumelmonster . Please rename me from "Contributor" to, for example "Previous maintainer" since I won't be active here anymore. You can also remove me from contributors on GH repo if you want. Thx!

**Comment by krumelmonster** [comment]
> Please rename me from "Contributor" to, for example "Previous maintainer" since I won't be active here anymore

[AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Rules_of_submission) suggest to list former maintainers as contributors so I assume it will be clear that you're not a contact for the project anymore. If you don't like to be listed as a contributor, I can remove that line as other versions don't seem to be conventional.

> If there were previous maintainers, put them as contributors.

**Comment by TomaszGasior** [comment]
Ok, let's do what you think is good. :)
