### ISSUE TITLE
repo still maintained?

### ISSUE THREAD

**Issue by oberon-manjaro** [lah7/gtk3-classic#22]
Hi @krumelmonster .
I understand that you inherited this repo from @TomaszGasior 
Now I am wondering why the only commits I can see since Tomasz' last commit in May are the ones adjusting maintainer information while the rest hasn't been touched since.
Upstream **gtk3** is meanwhile at **3.24.10** while the PKGBUILD here of course is still at **3.24.8**.
I further saw that Archlinux has since moved on to [meson build](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gtk3#n39).
Being the maintainer of the Manjaro **gtk-classic** package I am now a little concerned about this repo being properly maintained and I would like to ask you what your further plans with this are.
Thank you.
@philmmanjaro

**Comment by krumelmonster** [comment]
@philmmanjaro I wasn't able to look into the project right away but it's up-to-date now and I'm positive I'll be able to get it up-to-date in time from now on.
I will also take a look at meson.
Thank you for the friendly reminder.
