### ISSUE TITLE
Reinstate mouse scrolling to switch between tabs (GTK2 feature)

### ISSUE THREAD

**Issue by lah7** [lah7/gtk3-classic#25]
### What should be patched?
GTK2 had the ability to use the mouse wheel to switch between tabs (`GTKNotebook`), but GTK3 removed this feature. Each GTK3 application is expected to add code should they wish to support the behaviour, [for example, this commit in Caja](https://github.com/mate-desktop/caja/commit/0b4c7a6b8c25afb987d08bfd2c4c9be57de23960).

* https://gitlab.gnome.org/GNOME/gtk/issues/234 (contains a patch)
* https://bugzilla.gnome.org/630226 (original bug when feature was removed)

### Commits

I attempted to apply the patch [`0001-GtkNotebook-Add-scroll-event.patch`](https://gitlab.gnome.org/GNOME/gtk/uploads/7b9a377b51ee61869e2928bf15f58017/0001-GtkNotebook-Add-scroll-event.patch) myself prior to opening this issue, but I'm unfamiliar with C and ran into an error. As the bug report's patch is 4 years old, it'll probably need further tweaking for the latest GTK codebase:

```
make[2]: Entering directory '/home/virtualbox/Desktop/gtk+-3.24.8/gtk'
  CCLD     libgtk-3.la
/usr/bin/ld: .libs/libgtk_3_la-gtknotebook.o: relocation R_X86_64_PC32 against undefined symbol `gtk_notebook_scroll' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

_(Output from Ubuntu MATE 19.04, as I was doing some testing there)_

Thanks in advance!

**Comment by krumelmonster** [comment]
Thanks for your suggestion. I tested the patch but it doesn't seem to have the desired (or any?) effect, at least not in gtk3-widget-factory. I'll investigate further.
