### ISSUE TITLE
Other Locations still visible

### ISSUE THREAD

**Issue by Vistaus** [lah7/gtk3-classic#27]
I installed the latest version of gtk3-mushrooms and everything seems to have applied fine: typeahead is restored, context menu is no longer a popover, colored sidebar icons, etc. But Other Locations is still there. How come?

**Comment by lah7** [comment]
This issue is quite old - and we have new maintainer! Under the latest version of `gtk3-classic` (3.24.27), I'm not seeing "Other Locations" in the file chooser's sidebar.

If this is still an issue, please feel free to reopen this issue.
