### ISSUE TITLE
Errors in console output (and logfile) about non-existent "inhibit" are back

### ISSUE THREAD

**Issue by MR-Diamond** [lah7/gtk3-classic#29]
Manjaro XFCE (Xfce 4.14.1) - gtk3-classic  3.24.13+23-1

I landed here after searching and reading this old message on the Manjaro Forum:
https://forum.manjaro.org/t/gtk3-classic-gtk3-mushrooms-gtk3-with-my-own-patches/30230/131

> In XFCE, console errors like this should not be shown now: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist". It’s annoying to see it while using gedit or xed from command line.

The described issue is still present today: as I launch gedit from the Terminal or GUI (in this case this error is continuosly reported in the log file ~/.xsession-errors)  I always read:

`(org.gnome.gedit:28461): Gtk-WARNING **: 17:39:00.039: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Inhibit”`

I see that the commit, from 22 September 2018, which should suppress this error message, is here https://github.com/krumelmonster/gtk3-mushrooms/commit/c5f1b69b1d37a2723b043727965e65a1e7e42d01 but maybe in the meantime something is changed, since this error message occurs again.

**Comment by lah7** [comment]
The issue's a year old - if you still use this package, it might be worth trying the latest version and see if still happens under the latest GTK3 + these patches?

**Comment by MR-Diamond** [comment]
Hi, I'm on latest version and I no longer see the mentioned error message.
However; many thanks for maintaining gtk3-classic, very appreciated!

**Comment by lah7** [comment]
I just recently took over this repository - credit goes to others for the existing patches and AUR packaging 🏅 

Good to know the warning has disappeared. :+1:
