### ISSUE TITLE
Missing some icon when using kde and breeze theme

### ISSUE THREAD

**Issue by huyz-git** [lah7/gtk3-classic#35]
### Bug Description
When using kde and breeze theme, some gtk3 application miss some icon.
In `gedit`, The icon of "open" "save" and "cut" "copy" "paste" is missing:
![Screenshot_20210429_190135](https://user-images.githubusercontent.com/22879638/116541492-1ae10680-a91e-11eb-9543-e64e80fa9631.png)

However, this behaviour only happends in **some** application. 
In `simple-scan`, the "save" icon is shown correctly:
![Screenshot_20210429_190601](https://user-images.githubusercontent.com/22879638/116541640-49f77800-a91e-11eb-9cff-14ea042037a7.png)

### Expected Behaviour
Of course breeze theme do have icon of "open" "save" and "cut" "copy" "paste", so `gedit` should show the correct icon.

### Screenshots
If applicable, add screenshots to help visualize the problem.

### Environment
 - OS: Archlinux
 - Desktop Environment: KDE
 - gtk3-classic Version: 3.24.29

**Comment by lah7** [comment]
A workaround is to install `gnome-icon-theme` to restore the missing icons. `gedit` isn't respecting another GTK3 icon theme for some reason.

For a classic `gedit` experience, consider `pluma` (MATE) instead.

**Comment by huyz-git** [comment]
Thanks for this workaround.
Using this workaround, I do some tries and find that `gedit` is actually using icon `gtk-cut` `gtk-copy` `gtk-delete` `gtk-open` `gtk-paste` `gtk-save` `gtk-select-all`. And these icon name doesn't exist in breeze theme.
For icon theme (e.g. papirus) that contains these icon name, `gedit` will show these icon correctly.
For breeze icon theme user, just create `~/.local/share/icons/breeze/actions/16`, and link the proper icon with the `gtk-` name.
