### ISSUE TITLE
Slow panel loading during system startup

### ISSUE THREAD

**Issue by robson-66** [lah7/gtk3-classic#36]
Why is the panel and applets so slow to load in the latest version of `gtk3-classic`? I am using DE Xfce4

**Comment by lah7** [comment]
I don't use XFCE so I wouldn't have observed this. Something might have changed in `gtk3` upstream; it could be fixes from the last update, or it could be a coincidental system update.

Assuming a fully up-to-date Arch system, please could you check:

1. If it's still slow after installing `gtk3` 3.24.30 (replacing `gtk3-classic`)?
2. If it's still slow after installing the [previous version of `gtk3-classic` 3.24.29](https://github.com/lah7/gtk3-classic/releases/tag/3.24.29)?

We need to rule out whether it's `gtk3` or `gtk3-classic` or neither.

---

If it's still an issue in `gtk3`, then that would explain the slowness. It could be addressed here if someone wishes to find out what changed in GTK3 and create a patch, or create a bug report and/or fix it upstream. You could use a lock your `gtk3-classic` package to an older version in the meantime.

If it's definitely `gtk3-classic`, clone this repository and try commenting out (`#`) patches from the [PKGBUILD from this repository](https://github.com/lah7/gtk3-classic/blob/master/PKGBUILD). Build & install the package using:

    makepkg --skipint
    sudo pacman -U ./*.zst

The newest patch was `appearance__fix_black_border.patch` although I _don't think_ that would cause of any slowness.

**Comment by robson-66** [comment]
There are no problems on `GTK3`.

**Comment by robson-66** [comment]
It turned out that the problem was doing `appearance__fix_black_border.patch`, after rebuilding `gtk3-classic` disabling this patch `#` the panel loads normally.

**Comment by lah7** [comment]
Good to know. How slow are the applets/panels for you? Like, a few seconds between loading each one?

I can't replicate this on a minimal Arch install in VirtualBox. I installed XFCE (+ Xorg & SDDM), added another panel and a few widgets but can't see any difference in load speeds.

If many others are having the same issue, we can revert the patch.

**Comment by robson-66** [comment]
For example, I have a `pa-applet` on xfce4-panel and as you know it is based on `GTK2` as well as the `networkmanager` applet simply these applets used to require about 4 seconds to load, and now it is after rebuilding without this patch they load instantly.

**Comment by lah7** [comment]
Still unable to reproduce. I installed `pa-applet-git` (AUR), `network-manager-applet` and another application that supports both GTK Status Icon and AppIndicator3 for the tray icon. Load times are unaffected.

Let's leave this issue open for now in case anyone has further feedback.

**Comment by robson-66** [comment]
I forgot to add that on my Xfce4 I use `compiz`, and I have `xfce4-panel-compiz` installed, but I don't think it matters because when I turned it off for a test and logged into xfwm4, the effect was the same.

**Comment by robson-66** [comment]
Maybe it has something to do with the theme I use https://github.com/robson-66/DarkCold

**Comment by robson-66** [comment]
All in all it can be closed at most I will edit `PKGBUILD` and build without the recently introduced patch.
