### ISSUE TITLE
Request: Restore original accent behavior

### ISSUE THREAD

**Issue by fulalas** [lah7/gtk3-classic#37]
I reported this odd new behavior [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/4095) thinking it was a bug, but they said it was [changed by design](https://blog.gtk.org/2021/03/24/input-revisited/).

BTW, nice work! :)

**Comment by Okxa** [comment]
So I did not see this issue, sorry for the duplicate, but anyways, there is actually a patch already for this, if that is something you consider adding to gtk3-classic:

When typing characters with [deadkeys](https://en.wikipedia.org/wiki/Dead_key), gtk3 currently shows an underline, which is very annoying to some people (such as myself).

### Approach

There is already an [patched version of gtk3 on AUR](https://aur.archlinux.org/packages/gtk3-no_deadkeys_underline), using [this patch](https://aur.archlinux.org/cgit/aur.git/plain/no_deadkeys_underline.patch?h=gtk3-no_deadkeys_underline):

```diff
diff --git a/gtk/gtkimcontextsimple.c b/gtk/gtkimcontextsimple.c
index a7ac95e47c..237ddc0e72 100644
--- a/gtk/gtkimcontextsimple.c
+++ b/gtk/gtkimcontextsimple.c
@@ -1115,7 +1115,7 @@ gtk_im_context_simple_get_preedit_string (GtkIMContext   *context,
                   gunichar ch;
                   gboolean need_space;

-                  if (is_dead_key (priv->compose_buffer[i]))
+                  if (FALSE && is_dead_key (priv->compose_buffer[i]))
                     {
                       ch = dead_key_to_unicode (priv->compose_buffer[i], &need_space);
                       if (ch)
```

I already tested the patch with the gtk3-classic PKGBUILD, by manually adding the patch file to the folder (and in PKGBUILD sources) and patching with `patch -p1 < ../no_deadkeys_underline.patch` in `prepare()`, however you might want to add it to your patching system.

**Comment by lah7** [comment]
Thanks for this. Dead keys isn't something I knew about, but I'll certainly get it added into `quilt` and push an update.

**Comment by fulalas** [comment]
It works perfectly! Thanks once again :)
