### ISSUE TITLE
No printers 

### ISSUE THREAD

**Issue by jEsuSdA** [lah7/gtk3-classic#6]
No printers are showed on printing dialog.
using 3.2.26 

![imagen](https://user-images.githubusercontent.com/5833446/36301308-a1d0d96c-1304-11e8-9892-1478c99c290f.png)

**Comment by TomaszGasior** [comment]
Did you installed optional dependences of `gtk3-mushrooms` package — especially `libcups`?

**Comment by jEsuSdA** [comment]
Yes. As you can see, the configuration printer dialog shows the installed printers on systems.
Rolling back to official gtk3 packages the printers appears again.

**Comment by TomaszGasior** [comment]
Are you sure you checked optional dependencies of my package? Did you installed `colord` package? GTK's print dialog requires it. Arch Linux's GTK3 package specifies `colord` as hard dependency, `gtk3-mushrooms` has it in optional dependencies.

**Comment by jEsuSdA** [comment]
I'll try to check all dependencies.
Are other than these? 
	atk cairo libxcursor libxinerama libxrandr libxi libepoxy gdk-pixbuf2
	libxcomposite libxdamage pango shared-mime-info at-spi2-atk wayland libxkbcommon
json-glib librsvg wayland-protocols desktop-file-utils mesa gtk-update-icon-cache

Thanks! ;)

**Comment by TomaszGasior** [comment]
You listed hard dependencies. And you should check **optional** dependencies too. Please see ss: https://i.imgur.com/dTNuKFh.png

**Comment by TomaszGasior** [comment]
`colord` must be installed to see printers in GTK's printing dialog. If `colord` is not installed, printers are shown in `system-config-printers` but not in GTK dialog.
`colord` is hard dependency for `gtk3` but for `gtk3-mushrooms` is only optional dependency — user is able to use GTK3 apps without ability to print from them.
