### ISSUE TITLE
Feature Request:   Toggle Location Entry Button 

### ISSUE THREAD

**Issue by revast** [lah7/gtk3-classic#7]
hi, it would be cool to have a button for that instead of a hidden shortcut CTRL+L 
As nemo also has one, there also exists a proper svg icon for that:

![2018-02-16 17-16-53](https://user-images.githubusercontent.com/8189198/36318449-2db25042-1340-11e8-83ee-17080e6abd0e.png)

quick mockup for save dialog:

![2018-02-16 17-15-592](https://user-images.githubusercontent.com/8189198/36329399-1ef7c39a-1366-11e8-8da8-4c05eadda89b.png)

also a means to have location entry toggable in a dconf setting would be great

**Comment by TomaszGasior** [comment]
In my opinion button for toggling visibility of location bar is not needed. Path bar is more friendly for beginners. Location bar is useful for advanced users, who are often keybord-oriented and who have not problems with using shortcuts. Also I want to keep my patches simple to maintain in the future.

But gsettings (not dconf, dconf is backend for gsettings mechanism) setting for forcing location field is interesting. ;-) I will investigate it in the future. Currently I am adding it to TODO list.
