### ISSUE TITLE
gtk3 3.22.30

### ISSUE THREAD

**Issue by oberon-manjaro** [lah7/gtk3-classic#9]
I have updated the Manjaro PKGBUILDS using 3.22.30 source.
The multilib version needed a few new depends, apart from that the patches applied cleanly and I don't see any apparent problems.
Could you let me know if any other adjustments will be needed? Thank you.
https://github.com/manjaro/packages-extra/commit/c4ec55543f38f8789c606f91f8c2d0be11f0b7c7
https://github.com/manjaro/packages-multilib/commit/cef395a70449a689775ad0e931f63c76aba7fc10

**Comment by TomaszGasior** [comment]
Sorry for delayed response. I was busy on my other project.

Your changes are done properly, as always. ;p
